### ISSUE TITLE
Authentication Failed when i run nexpose_ticketing servicenow under bin folder

### ISSUE THREAD

**Issue by anujamps** [rapid7/nexpose_ticketing#11]
Integration with ServiceNow-
1.Modified the servicenow.config
2.Modified ticket_service.config
3.Issue when I am running the command "nexpose_ticketing servicenow"

**C:/Ruby23/lib/ruby/gems/2.3.0/gems/nexpose-3.3.2/lib/nexpose/connection.rb:76:in
 `rescue in login': NexposeAPI: Login Failed (Nexpose::AuthenticationFailed)
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nexpose-3.3.2/lib/nexpose/connec
tion.rb:67:in `login'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nexpose_ticketing-1.3.0/lib/nexp
ose_ticketing/ticket_repository.rb:34:in `nexpose_login'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nexpose_ticketing-1.3.0/lib/nexp
ose_ticketing/ticket_service.rb:96:in `setup'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nexpose_ticketing-1.3.0/lib/nexp
ose_ticketing.rb:7:in `start'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/nexpose_ticketing-1.3.0/bin/nexp
ose_ticketing:45:in `<top (required)>'
        from C:/Ruby23/bin/nexpose_ticketing:22:in `load'
        from C:/Ruby23/bin/nexpose_ticketing:22:in `<main>'

C:\Ruby23\lib\ruby\gems\2.3.0\gems\nexpose_ticketing-1.3.0\bin>**

I am getting authentication failed when am trying to run "nexpose_ticketing servicenow" under bin folder.
My credentials are correct, they have full admin access and are working in the web ui. Please le me know if you have any inputs about this issue

Thanks,
Anusha

**Comment by aRobinson-R7** [comment]
Hi @anujamps 
This is usually caused by a misconfiguration in your ticket_service.config file.
The file is a YAML file, and so depends on the format of the data inserted.

Can you ensure the nexpose_data section of the file looks like the below:
:nexpose_data:
  \# (M) Nexpose console hostname.
++:nxconsole: 127.0.0.1 
  \# (M) Nexpose username.
++:nxuser: nxadmin
  \# (M) Nexpose password.
++:nxpasswd: nxadmin

with no quotation marks around the values? (and two spaces before each :field:, here represented by + as github formats the message)
Thanks

**Comment by peterjmcg** [comment]
If you have non-alphanumeric characters in username or password you may have to escape or enclose in double quotes.

**Comment by namanrg** [comment]
can someone help on this issue putting it here as mine is an issue with servicenow and nexpose integration too. 
![image](https://user-images.githubusercontent.com/28726043/31320335-8cc0dc96-ac90-11e7-92f6-a59ece03be23.png)

**Comment by dvalente-r7** [comment]
Please conta
