### ISSUE TITLE
Provide natural IDs for Nexpose Vulnerabilities

### ISSUE THREAD

**Issue by gschneider-r7** [rapid7/nexpose_ticketing#8]
Disclaimer: I'm not totally familiar with the workflow with this tool so feel free to correct me on any wrong assumptions.

@ben-git-hub99 opened rapid7/nexpose-client#210 with a need to convert surrogate vulnerability IDs to natural IDs, since the ticketing gem uses surrogate IDs when constructing a "Nexpose ID" (site + asset + vuln ID numbers?)

Since Nexpose does not have any API endpoints for this and probably will not, it seems like it would be easier for the ticketing gem to be able to expose the natural IDs somewhere here.

The alternative (as I proposed in the other issue) is to generate a bulk dump of vulnerability IDs from Nexpose to use for lookups in a script that is working off of both the ticketing and Nexpose data.

**Comment by JJCassidy-R7** [comment]
The ticketing gem uses the NXID for uniquely identifying a generated ticket to ensure it's not possible for a duplicate to exist no matter the scan or configuration options (collapse by IP, collapse by vulnerability id or 1:1 mapping of vulnerability to ticket). What values are used to generate this ID is dependant on the user configuration options - I would not recommend trying to strip these individual values out of the generated NXID.

@ben-git-hub99 - In terms of getting the vulnerability nexpose ID/'natural ID' - why is this required? What is the use case? Why is the vulnerability ID not sufficient (supplied in the ticket worknotes)?

**Comment by gschneider-r7** [comment]
I think Ben is trying to programmatically build a scan template for remediation scanning based on the vulnerabilities in the tickets, but Nexpose does not expose a way to do this (or anything really) with the surrogate IDs (numbers). Natural IDs are needed to find vulnerabilities/checks to use in scan templates.

**Comment by JJCassidy-R7** [comment]
Gotcha. 

I believe we include the natural solution ID but not the natural vulnerability ID (and they can differ).

Sounds like a legitimate use case. I'll get a ticket onto our backlog - you should see this being added to ticket worknotes as of the next release.

**Comment by ben-git-hub99** [comment]
Hi @JJCassidy-R7,

I opened https://github.com/rapid7/nexpose-client/issues/217 to provide a use case. Basically, I am trying to utilize the vulnid to provide additional information (that may have not been included in the ticket). 

Previously, we would have issues reopen because the vulnid was already resolved. This meant that the vulnerability couldn't be identified and based on my template would launch a full scan.

Anyways, updating the ticket gem to include the natural vuln id will require a rewrite of various parts of my code. Keep me in the loop if this gets out of the backlog. I will start refactoring and rewriting.
